# Generated by Django 5.2.6 on 2025-10-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_certificaterequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterequest',
            name='certificate_type',
            field=models.CharField(choices=[('good_moral', 'Good Moral Certificate'), ('enrollment', 'Certificate of Enrollment'), ('registration_form', 'Registration Form'), ('tor', 'Transcript of Records'), ('cog', 'Certificate of Grades'), ('diploma', 'Diploma')], max_length=50),
        ),
    ]
